### ISSUE TITLE
Non-zero status code returned while running Add node.

### ISSUE THREAD

**Issue by R4mR4m** [AIDajiangtang/Segment-Anything-CSharp#1]
I have this error message:

` '[ErrorCode:RuntimeException] Non-zero status code returned while running Add node. Name:'/blocks.7/attn/Add_2' Status Message: bad allocation' `

while running:            
 
`var results = this.mEncoder.Run(inputs);` 

Have you experienced that?

**Comment by R4mR4m** [comment]
The exception was thrown  due to an incorrect version of OnnxRuntime during the model conversion

**Comment by AIDajiangtang** [comment]
Hi,
can you tell me how did you fix it? what version of OnnxRuntime is OK?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AIDajiangtang/SAMTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月27日(星期二) 晚上6:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [AIDajiangtang/SAMTool] Non-zero status code returned while running Add node. (Issue #1)





 
The exception was thrown  due to an incorrect version of OnnxRuntime during the model conversion

**Comment by R4mR4m** [comment]
The model conversion environment should use the same OnnxRuntime version as the visual studio project Nuget package.  

 My environment had onnxruntime  1.14.1 while the project uses 1.15.0. 

I updated my environment onnxruntime  package to 1.15.0, converted the model again and it worked with no problem.

**Comment by AIDajiangtang** [comment]
In my case, I have the same problem as you occasionally, but it should not be the cause of the OnnxRuntime version. I found that when the problem occurs, the memory usage of my computer is close to the peak，I googled and the answer is because of insufficient memory




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AIDajiangtang/SAMTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月30日(星期五) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AIDajiangtang/SAMTool] Non-zero status code returned while running Add node. (Issue #1)





 
The model conversion environment should use the same OnnxRuntime version as the visual studio project Nuget package.
 
My environment had onnxruntime  1.14.1 while the project uses 1.15.0.
 
I updated my environment onnxruntime  package to 1.15.0, converted the model again and it worked with no problem.

**Comment by R4mR4m** [comment]
I was getting this error every single time I tried to run the application. Then looked at my PC resource usage and realized that it was not the memory shortage of my computer, so there had to be another problem. 

After converting the model using onnxruntime  1.15.0 I was able to run the application.

**Comment by AIDajiangtang** [comment]
Thank you for your reply, if you find new information, please share it with me


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AIDajiangtang/SAMTool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月30日(星期五) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AIDajiangtang/SAMTool] Non-zero status code returned while running Add node. (Issue #1)





 
I was getting this error every single time I tried to run the application. Then looked at my PC resource usage and realized that it was not the memory shortage of my computer, so there had to be another problem.
 
After converting the model using onnxruntime  1.15.0 I was able to run the application.

**Comment by R4mR4m** [comment]
for better memory management add session options to both the encoder and decoder: 

` var options = new SessionOptions();`
` options.EnableMemoryPattern = false;`
` options.EnableCpuMemArena = false; `

`this.mEncoder = new InferenceSession(modelEncoder, options);`
`this.mDecoder = new InferenceSession(modelDecoder, options);`

**Comment by AIDajiangtang** [comment]
> ` options.EnableMemoryPattern = false;`
> `options.EnableCpuMemArena = false;`

thanks for that
